#%RAML 1.0
title: ACME Banking API
description: |-
  Base URI = URL final donde estara la app, mycompany.com/api

  This API offers acces to personal banking data
mediaType:
  - application/json
version: v1  
protocols:
  - HTTP
  - HTTPS
#register new datatypes  
types:
  Account: !include Account.raml

/accounts:
  post:    
    displayName: Create a new account
    body:
      type: Account
    responses:
      201:
      400:
        headers:
          Accept:
            example: application/json              
        body:
          example:
            type: Missing attribute
            title: Body structure incomplete
            detail: Body is missing the account id.   

  /{account_id}:
    get:
      displayName: Get account information for a specific account ID
      headers:
          Accept:
            required: false 
      responses:
        200:  
          headers:
            Cache-Control:
              example: max-age=604800 #1 Week
    put:      
      displayName: Update account information for a specific account ID
      responses:
        201: 
        503:
          headers:
          body:
            example:
              type: Service Unavailable
              title: Service Unavailable
              detail: The account service is not available
    delete:
      displayName: Delete an account with a specific account ID 
      responses:
        202:
        204:
    /transactions:
      get:
        displayName: Get all transactions for a specific account ID 
        headers:
          Accept:
            required: false 
        responses:
          200:  
            headers:
              Cache-Control:
                example: max-age=604800 #1 Week


/customers:
  get:
    displayName: Get all customers in the bank  
    headers:
          ##Accept?: não obrigatorio
          Accept:
            required: false ##mesmo sentido da linha acima comentada
            example: application/json  
    body:        
    responses:
      200:  
        headers:
          Cache-Control:
            example: max-age=604800 #1 Week              
        body:
  post:
    displayName: Create a new customer
    responses:
      201:
      400:
        headers:
        body:
          example:
            type: Missing attribute
            title: Body structure incomplete
            detail: Body is missing the account id.  
       

  /{customer_id}:
    get:
      displayName: Get information for a specific ID
      headers:
          Accept:
            required: false      
      responses:
        200:  
          headers:
            Cache-Control:
              example: max-age=604800 #1 Week        
    patch:
      displayName: Patch information for a specific ID
      responses:
        204:
        503:
          headers:
          body:
            example:
              type: Service Unavailable
              title: Service Unavailable
              detail: The custumer service is not available  
    delete:      
      displayName: Delete information for a specific ID
      responses:
        202:
        204:
    /accounts:
      get:
        displayName: Get all accounts for a specific customer ID  
        headers:
          Accept:
            required: false 
        responses:
          200:  
            headers:
              Cache-Control:
                example: max-age=604800 #1 Week

/transactions:
  post:    
    displayName: Create a new transaction
    responses:
      201:
      400:
        headers:
        body:
          example:
            type: Missing attribute
            title: Body structure incomplete
            detail: Body is missing the account id.  
  /{transaction_id}:
    get:
      displayName: Get transaction information for a specific transaction ID
      headers:
          Accept:
            required: false 
      responses:
          200:  
            headers:
              Cache-Control:
                example: max-age=604800 #1 Week
