#%RAML 1.0
title: ACME Banking API
description: |-
  Base URI = URL final donde estara la app, mycompany.com/api

  This API offers acces to personal banking data
mediaType:
  - application/json
protocols:
  - HTTP
  - HTTPS
/accounts:
  get:
    displayName: Get All Accounts info
/customers:
  get:
    displayName: Get All Customers info
/transactions:
  get:
    displayName: "Get All Transactions "
