#%RAML 1.0
title: ACME Banking API
description: |-
  Base URI = URL final donde estara la app, mycompany.com/api

  This API offers acces to personal banking data
mediaType:
  - application/json
version: v1  
protocols:
  - HTTP
  - HTTPS


/accounts:
  post:    
    displayName: Create a new account

  /{account_id}:
    get:
      displayName: Get account information for a specific account ID
      responses:
        200:
    put:      
      displayName: Update account information for a specific account ID  
    delete:
      displayName: Delete an account with a specific account ID 
    /transactions:
      get:
        displayName: Get all transactions for a specific account ID 
        responses:
          200:


/customers:
  get:
    displayName: Get all customers in the bank    
  post:
    displayName: Create a new customer
       

  /{customer_id}:
    get:
      displayName: Get information for a specific ID
      responses:
        200:
    patch:
      displayName: Patch information for a specific ID
    delete:      
      displayName: Delete information for a specific ID
    /accounts:
      get:
        displayName: Get all accounts for a specific customer ID  
        responses:
          200:

/transactions:
  post:    
    displayName: Create a new transaction
  /{transaction_id}:
    get:
      displayName: Get transaction information for a specific transaction ID
