#%RAML 1.0 ResourceType


post:    
  displayName: Create a new <<resourcePathName | !singularize >>
  body:
    type: <<resourcePathName | !singularize | !uppercamelcase>>
  responses:
    201: 
      body:
        example: OK
      headers:
        Location:
          example: /<<resourcePathName>>/acc-123
    400:
      headers:
        Accept:
          example: application/json              
      body:
        example:
          type: Missing attribute
          title: Body structure incomplete
          detail: Body is missing the account id.