#%RAML 1.0 NamedExample
value:
  customerID: 8f19cb50-3f57-4d38
  firstName: Joni
  lastName: Souza
  displayName: Joni Souza
  address: 
    addressLine1: 1234 Calle
    addressLine2: Apt.#620
    city: Blumenau
    state: Santa Catarina
    zipCode: '89023372'
    country: Brazil
  phone: 47-000-0000
  email: johndoe@example.com
  ssn: 123-45-7890
  dateOfBirth: 1983-01-01
