#%RAML 1.0
title: ACME Banking API
mediaType:
  - application/json

types:
    Customer: !include datatypes/Customer.raml
    Account: !include datatypes/Account.raml
    Transaction: !include datatypes/Transaction.raml
    CustomErrorMessage: !include datatypes/CustomErrorMessage.raml  

/customers:
  get:   
    headers:
      Accept?: 
    responses:
      200:
        headers:
          Cache-Control: 
          Expires: 
            type: datetime
        body:      
          application/json:
          application/xml:            
      404:
        body:
          properties:
            statusCode: string
            message: string         
      406:
        body:
          properties:
            statusCode: string
            message: string       
  post:    
    body:
    responses:
      201:
        headers:
          Location: 
        body:        
      503:
        body:
          properties:
            statusCode: string
            message: string  
  /{customer_id}:
    get:     
      responses:
        200:
          body:
        404:
          body:
            properties:
              statusCode: string
              message: string    
    patch:
      body:
      responses:
        204:    
        501:
          body:
            properties:
              statusCode: string
              message: string                              
    delete: 
      responses:
        200:
          body:
        404:
          body:
            properties:
              statusCode: string
              message: string    
    /accounts:
      get:    
        responses:
          200:
            body:    
          404:
            body:
              properties:
                statusCode: string
                message: string    

/accounts:
  post:
    body:
    responses:
      201:
        headers:
          Location: 
        body:     
      503:
        body:
          properties:
            statusCode: string
            message: string    
  /{account_id}:
    get:      
      responses:
        200:
          body:
        404:
          body:
            properties:
              statusCode: string
              message: string    
    put:
      body:
      responses:
        200:
          body:
        201:
          headers:
            Location: 
          body:         
        501:
          body:
            properties:
              statusCode: string
              message: string   
    delete:
      responses:
        200:
          body:
        404:
          body:
            properties:
              statusCode: string
              message: string    
    /transactions:
      get:     
        responses:
          200:
            body:   
          404:
            body:
              properties:
                statusCode: string
                message: string    

/transactions:
  post:
    body:
    responses:
      201:
        headers:
          Location: 
        body:       
      503:
        body:
          properties:
            statusCode: string
            message: string  
  /{transaction_id}:
    get:
      responses:
        200:
          body:
        404:
          body:
            properties:
              statusCode: string
              message: string    

