#%RAML 1.0 DocumentationItem
title: Getting Started with ACME Bank API
# Para usar markdown diretamente, utiliza-se Pipe (|)
content: |
  **ACME BANK** API Offers access to *customers*, *accounts* and *transactions* data,

  So we offer these resources:
    - Custumers
    - Accounts
    - Transaction

    # h1 Heading 8-)
    ## h2 Heading
    ### h3 Heading
    #### h4 Heading
    ##### h5 Heading
    ###### h6 Heading


    ## Horizontal Rules

    ___

    ---

    ***

    
    ~~Strikethrough~~  