#%RAML 1.0 DocumentationItem
title: Getting Started with ACME Bank API
# Para usar markdown diretamente, utiliza-se Pipe (|)
content: |
  **ACME BANK** API Offers access to *customers*, *accounts* and *transactions* data,

  So we offer these resources:
    - Custumers
    - Accounts
    - Transaction

  ``` js
  var foo = function (bar) {
    return bar++;
  };

  console.log(foo(5));
  ```

  ## Images
  ![Stormtroopocat](https://octodex.github.com/images/stormtroopocat.jpg "The Stormtroopocat")

  ## Tables

  | Option | Description |
  | ------ | ----------- |
  | data   | path to data files to supply the data that will be passed into templates. |
  | engine | engine to be used for processing templates. Handlebars is the default. |
  | ext    | extension to be used for dest files. |
    > Blockquotes can also be nested...
    >> ...by using additional greater-than signs right next to each other...
    > > > ...or with spaces between arrows.

    # h1 Heading 8-)
    ## h2 Heading
    ### h3 Heading
    #### h4 Heading
    ##### h5 Heading
    ###### h6 Heading


    ## Horizontal Rules

    ___

    ---

    ***

    
    ~~Strikethrough~~  